"""Driver code synthesis helpers."""

from .classify_device import (
    ClassifyResult,
    EVAL_CLASSES,
    EVAL_CLASS_DISPLAY,
    EVAL_CLASS_MEMORY,
    EVAL_CLASS_MULTI_CHANNEL,
    EVAL_CLASS_RTC,
    EVAL_CLASS_SINGLE_CHANNEL,
    classify_device,
)
from .adapter_generator import (
    API_CONTRACT_SCHEMAS,
    AdapterContractError,
    GeneratedAdapter,
    generate_adapter,
)
from .synthesis_schema import (
    API_CONTRACT_BRANCHES,
    TEST_PLAN_SCHEMA,
    build_prompt_schema_hint,
    synthesis_schema_for,
    validate_synthesis_response,
)
from .route import (
    RUNTIME_GPIO_DISCRETE,
    RUNTIME_GPIO_PULSE,
    RUNTIME_I2C,
    RUNTIME_SPI,
    RUNTIME_UART,
    RoutingResult,
    SLAVE_GPIO_LEVEL,
    SLAVE_GPIO_PULSE,
    SLAVE_I2C_DISPLAY,
    SLAVE_I2C_MEMORY,
    SLAVE_I2C_REGISTER,
    SLAVE_SPI_GENERIC,
    SLAVE_UART_BOT,
    SPI_SUB_COMMAND,
    SPI_SUB_REGISTER,
    SPI_SUB_STREAM,
    route,
)
from .ir_to_expected_transactions import (
    ExpectedTransaction,
    derive_expected_transactions,
)
from .prompt_builder import (
    SYSTEM_PROMPT as SYNTHESIS_SYSTEM_PROMPT,
    build_synthesis_prompt,
)
from .code_generator import (
    SynthesisBundle,
    SynthesisError,
    generate_synthesis,
)
from .consistency_check import (
    VERDICT_INCONSISTENT,
    VERDICT_L1,
    VERDICT_L2,
    VERDICT_LLM_ONLY,
    ConsistencyReport,
    StimulusConsistency,
    check_consistency,
    check_stimulus,
)
from .merge_test_plan import (
    CoverageMatch,
    CoverageReport,
    check_bundle_coverage,
    check_transaction_coverage,
)
from .runtime_probe import (
    ProbeError,
    ProbeMeta,
    ProbeOutcome,
    ProbeStimulus,
    build_probe_meta,
    build_probe_stimuli,
    build_probe_stimulus,
    probe_all_stimuli,
    probe_stimulus,
)
from .diagnosis_renderer import (
    SEVERITY_ERROR,
    SEVERITY_INFO,
    SEVERITY_WARNING,
    DiagnosisReport,
    DiagnosisSection,
    compose_diagnosis,
    render_compile_errors,
    render_consistency_report,
    render_coverage_report,
    render_critic_failures,
    render_feedback,
    render_invariants,
    render_probe_outcomes,
    render_synthesis_error,
)
from .invariants_tracker import (
    KIND_ADDRESS_SIZE,
    KIND_BYTE_ORDER,
    KIND_GPIO_TIMING,
    KIND_INIT_OPCODE,
    KIND_RAW_WIDTH,
    KIND_READ_ADDRESS,
    KIND_RUNTIME_PASS,
    KIND_SIGN,
    KIND_SPI_MASK,
    KIND_UART_FRAMING,
    Invariant,
    InvariantsTracker,
)
from .repair_context_selector import build_repair_context
from .repair_loop import (
    ALL_LAYERS,
    LAYER_LINK,
    LAYER_NONE,
    LAYER_PROBE,
    LAYER_SELF_CHECK,
    LAYER_SYNTAX,
    LAYER_SYNTHESIS,
    AttemptRecord,
    RepairLoopResult,
    run_repair_loop,
)
from .stub_compiler import stub_compile, StubCompileResult

__all__ = [
    "ClassifyResult",
    "EVAL_CLASSES",
    "EVAL_CLASS_DISPLAY",
    "EVAL_CLASS_MEMORY",
    "EVAL_CLASS_MULTI_CHANNEL",
    "EVAL_CLASS_RTC",
    "EVAL_CLASS_SINGLE_CHANNEL",
    "classify_device",
    "API_CONTRACT_SCHEMAS",
    "AdapterContractError",
    "GeneratedAdapter",
    "generate_adapter",
    "API_CONTRACT_BRANCHES",
    "TEST_PLAN_SCHEMA",
    "build_prompt_schema_hint",
    "synthesis_schema_for",
    "validate_synthesis_response",
    "RUNTIME_I2C", "RUNTIME_SPI", "RUNTIME_UART",
    "RUNTIME_GPIO_PULSE", "RUNTIME_GPIO_DISCRETE",
    "SLAVE_I2C_REGISTER", "SLAVE_I2C_MEMORY", "SLAVE_I2C_DISPLAY",
    "SLAVE_SPI_GENERIC", "SLAVE_UART_BOT",
    "SLAVE_GPIO_PULSE", "SLAVE_GPIO_LEVEL",
    "SPI_SUB_REGISTER", "SPI_SUB_STREAM", "SPI_SUB_COMMAND",
    "RoutingResult",
    "route",
    "ExpectedTransaction",
    "derive_expected_transactions",
    "SYNTHESIS_SYSTEM_PROMPT",
    "build_synthesis_prompt",
    "SynthesisBundle",
    "SynthesisError",
    "generate_synthesis",
    "VERDICT_L1",
    "VERDICT_L2",
    "VERDICT_LLM_ONLY",
    "VERDICT_INCONSISTENT",
    "StimulusConsistency",
    "ConsistencyReport",
    "check_stimulus",
    "check_consistency",
    "CoverageMatch",
    "CoverageReport",
    "check_transaction_coverage",
    "check_bundle_coverage",
    "ProbeError",
    "ProbeMeta",
    "ProbeStimulus",
    "ProbeOutcome",
    "build_probe_meta",
    "build_probe_stimulus",
    "build_probe_stimuli",
    "probe_stimulus",
    "probe_all_stimuli",
    "SEVERITY_ERROR",
    "SEVERITY_WARNING",
    "SEVERITY_INFO",
    "DiagnosisSection",
    "DiagnosisReport",
    "render_synthesis_error",
    "render_consistency_report",
    "render_coverage_report",
    "render_probe_outcomes",
    "render_compile_errors",
    "render_critic_failures",
    "render_invariants",
    "compose_diagnosis",
    "render_feedback",
    "KIND_BYTE_ORDER",
    "KIND_RAW_WIDTH",
    "KIND_SIGN",
    "KIND_INIT_OPCODE",
    "KIND_READ_ADDRESS",
    "KIND_SPI_MASK",
    "KIND_UART_FRAMING",
    "KIND_GPIO_TIMING",
    "KIND_ADDRESS_SIZE",
    "KIND_RUNTIME_PASS",
    "Invariant",
    "InvariantsTracker",
    "build_repair_context",
    "LAYER_SYNTHESIS",
    "LAYER_SYNTAX",
    "LAYER_SELF_CHECK",
    "LAYER_LINK",
    "LAYER_PROBE",
    "LAYER_NONE",
    "ALL_LAYERS",
    "AttemptRecord",
    "RepairLoopResult",
    "run_repair_loop",
    # shared helpers used by the RTOS extraction pipeline
    "stub_compile",
    "StubCompileResult",
]
